### PR TITLE
break statement not required

### PR DESCRIPTION
**Pull request by mayurnewase**

### CODE REVIEW

**Comment by mayurnewase** [comment]
I guess,test failing due to connection error?

**Comment by lhoestq** [comment]
We just fixed the other dataset on master. Could you rebase from master and push to rerun the CI ?

**Comment by lhoestq** [comment]
If I'm not wrong this function returns None if no main class was found.
I think it makes things less clear not to have a return at the end of the function.
I guess we can have one return in the for loop instead of the break statement, AND one return at the end to explicitly return None.
What do you think ?

**Comment by mayur741** [comment]
I guess current logic makes it more readable.
you can close this pr.

**Pull request closed without merging**
