### PR TITLE
JSON script

### PR DESCRIPTION
**Pull request by jplu**
Add a JSONS script to read JSON datasets from files.

### CODE REVIEW

**Comment by jplu** [comment]
The tests for the Wikipedia dataset do not pass anymore with the error:
```
To be able to use this dataset, you need to install the following dependencies ['mwparserfromhell'] using 'pip install mwparserfromhell' for instance'
```

**Comment by lhoestq** [comment]
This was an issue on master. You can just rebase from master.

**Comment by jplu** [comment]
Perfect! Indeed, it worked^^ Thanks @lhoestq

**Comment by patrickvonplaten** [comment]
Currently the dummy_data tests are always green because in a PR the dataset is not yet synchronized with aws. This PR fixes this: https://github.com/huggingface/nlp/pull/140 . 

Could you test `json` locally or wait until the PR: https://github.com/huggingface/nlp/pull/140 is merged ? :-)

**Comment by jplu** [comment]
Ok, I will wait #140 to be merged and then rebase :)

**Pull request merged**
