### PR TITLE
update mirror for RT dataset

### PR DESCRIPTION
**Pull request by jxmorris12**

### CODE REVIEW

**Comment by lhoestq** [comment]
Thanks for adding this mirror link :)

Could you run the following command to update the json file `dataset_infos.json` used to verify the integrity of the downloaded file ?

```
nlp-cli test ./datasets/rotten_tomatoes --save_infos --ignore_verifications
```

**Comment by jxmorris12** [comment]
done! @lhoestq

**Comment by lhoestq** [comment]
the build_doc CI fail comes from master and has been fixed on master

**Comment by jxmorris12** [comment]
done @thomwolf @lhoestq

**Pull request merged**
