### PR TITLE
Fix csv/json/txt cache dir

### LINKED ISSUE #444: Keep loading old file even I specify a new file in load_dataset
I used load a file called 'a.csv' by 
```
dataset = load_dataset('csv', data_file='./a.csv')
```
And after a while, I tried to load another csv called 'b.csv'
```
dataset = load_dataset('csv', data_file='./b.csv')
```
However, the new dataset seems to remain the old 'a.csv' and not loading new csv file.

Even worse, after I load a.csv, the load_dataset function keeps loading the 'a.csv' afterward. 

Is this a cache problem?

### PR DESCRIPTION
**Pull request by lhoestq**
The cache dir for csv/json/txt datasets was always the same. This is an issue because it should be different depending on the data files provided by the user.

To fix that, I added a line that use the hash of the data files provided by the user to define the cache dir.

This should fix #444

### CODE REVIEW

**Comment by thomwolf** [comment]
I think this is the way to go but I’m afraid this might be a little slow. I was thinking that we could use a high quality very fast non crypto hash like xxhash for these stuff (hashing data files)

**Comment by lhoestq** [comment]
Yep good idea, I'll take a look

**Comment by lhoestq** [comment]
I tested the hashing speed [here](https://colab.research.google.com/drive/1hlhP84kLIHmOzMRQN1h8x10hKWpXXyud?usp=sharing).
I was able to get 8x speed with `xxhashlib` (42ms vs 345ms for 100MiB of data).
What do you think @thomwolf ?

**Comment by lhoestq** [comment]
I added xxhashlib and some tests

**Pull request merged**
