### PR TITLE
add squad Spanish v1 and v2

### LINKED ISSUE #164: Add Spanish POR and NER Datasets
Hi guys,
In order to cover multilingual support a little step could be adding standard Datasets used for Spanish NER and POS tasks.
I can provide it in raw and preprocessed formats.

### PR DESCRIPTION
**Pull request by mariamabarham**
This PR add the Spanish Squad versions 1 and 2 datasets. 
Fixes #164

### CODE REVIEW

**Comment by lhoestq** [comment]
Nice ! :) 
Can we group them into one dataset with two versions, instead of having two datasets ?

**Comment by mariamabarham** [comment]
Yes sure, I can use the version as config name

**Comment by mariamabarham** [comment]
@lhoestq can you check? I grouped them

**Comment by lhoestq** [comment]
Awesome :) feel free to merge after fixing the test in the CI

**Comment by patrickvonplaten** [comment]
@mariamabarham - feel free to merge when you're ready. I only checked the dummy files. I did not run the SLOW tests.

**Pull request merged**
