### PR TITLE
GermEval 2014: new download urls

### PR DESCRIPTION
**Pull request by stefan-it**
Hi,

unfortunately, the download links for the GermEval 2014 dataset have changed: they're now located on a Google Drive.

I changed the URLs and bump version from 1.0.0 to 2.0.0.

### CODE REVIEW

**Review by lhoestq — COMMENTED** [review]
Thanks for fixing the url :) 

I noticed that you had to 'hack' the dummy data a bit. I managed to remove this hack and made another PR without the hack in #594

**Comment by lhoestq** [comment]
Closing this one as #594 is merged (same changes except the dummy data hack)

**Comment by vblagoje** [comment]
Awesome @stefan-it ! @lhoestq how soon can I use the fixed GermEval dataset in HF token classification examples?

**Comment by lhoestq** [comment]
I've manually updated the script on S3, so you can actually use it right now with
```python
from nlp import load_dataset

germeval = load_dataset("germeval_14")
```

**Comment by vblagoje** [comment]
Awesome. Not used yet but I am going to use it now. I've been working on an update for token classification examples and this was a missing piece. Thanks @stefan-it @lhoestq

**Pull request closed without merging**
